### PR TITLE
Fix the ordering of Blogs

### LINKED ISSUE #1534: Fix the ordering of blogs
There is a [FIXME](https://github.com/ocaml/ocaml.org/blob/master/script/rss2html.ml#L191) in the code ordering blogs by name concerning the following: a leading white space in the name of a blog will impact the ordering. So ideally leading white spaces should be removed before ordering, but arent' at the moment. I propose fixing that.

### PR DESCRIPTION
**Pull request by shreyaswikriti**
# Issue Description

Please include a summary of the issue.
Fixed the ordering of blogs ([FIXME](https://github.com/ocaml/ocaml.org/blob/master/script/rss2html.ml#L191))by removing the leading whitespace using String.trim function. Now leading whitespace won't impact ordering.

Fixes #1534

## Changes Made

Please describe the changes that you made.

* **Please check if the PR fulfills these requirements**

- [x] PR is descriptively titled and links the original issue above
- [ ] Before/after screenshots (if this is a layout change)
- [ ] Details of which platforms the change was tested on (if this is a browser-specific change)
- [ ] Context for what motivated the change (if this is a change to some content)

### CODE REVIEW

**Comment by shreyaswikriti** [comment]
@pitag-ha, Can you please look into this?

File: script/rss2html.ml [hunk 1]
```diff
@@ -189,7 +189,8 @@ let get_opml () =
   (* Broken feeds will be marked with [is_comment = true]. *)
   let opml = Opml1.of_atom ~head feeds in
   (* Sort by name.  (FIXME: one may want to ignore spaces.) *)
```
Comment (gs0510) [inline script/rss2html.ml]: You can remove the FIXME from this comment :)

File: script/rss2html.ml [hunk 2]
```diff
@@ -189,7 +189,8 @@ let get_opml () =
...
-  let by_name o1 o2 = String.compare o1.Opml1.text o2.Opml1.text in
+  let trimm str = String.trim str in
```
Comment (gs0510) [inline script/rss2html.ml]: You can name this function trim :) Alternatively you don't need to define this and instead can use `String.trim` directly in line 193. :)

**Review by gs0510 — CHANGES_REQUESTED** [review]
Thanks for your PR @shreyaswikriti! Looks good, some tiny changes needed :)

**Comment by shreyaswikriti** [comment]
@gs0510, Thanks for the review, I'll push the suggested changes.

**Comment by avsm** [comment]
This looks good, thank you for the contribution!
